---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helloworld-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: helloworld-svc
            port:
              number: 80
  tls:
  - hosts:
    - helloworld.jponc.dev
    secretName: jponc-dev-tls

---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-svc
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app:  helloworld

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-nginx
spec:
  selector:
    matchLabels:
      app: helloworld
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: helloworld-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: helloworld-volume
        configMap:
          name: helloworld
