apiVersion: batch/v1
kind: CronJob
metadata:
  name: route53ddns-cron
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: route53ddns-cron
            image: julianponce/route53ddns:latest
            envFrom:
            - secretRef:
                name: route53ddns-secret
          restartPolicy: OnFailure
