apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jponc-dev-crt
  namespace: default
spec:
  secretName: jponc-dev-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.jponc.dev"
  dnsNames:
  - "*.jponc.dev"
