apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ponce.julianalfonso@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - selector:
        dnsZones:
          - "jponc.dev"
      dns01:
        route53:
          accessKeyID: AKIAXWLKWOEZZBGC44XU
          hostedZoneID: Z02067441B1PJW358SFFQ
          region: global
          secretAccessKeySecretRef:
            name: aws-route-53-access-key
            key: secret-access-key
